version: '3'

services:
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "bash -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  mysql:
    build: ./mysql
    restart: unless-stopped
    env_file: ./mysql/.env
    volumes:
      - ../data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  onetable-api:
    build: ./node
    volumes:
      - ../onetable-api:/app
    ports:
      - "3100:3100"
    entrypoint:
      - bash
      - -c
      - |
        /wait-for-it.sh mysql:3306 -t 10
        npm run build
        pm2-runtime start ./pm2.config.js
